# Generated by Django 4.0.1 on 2022-01-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='axie',
            name='ronin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ronin'),
        ),
    ]
