# Generated by Django 4.0.1 on 2022-02-09 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axie',
            name='ronin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axies', to='users.ronin'),
        ),
    ]
